{% set name = "langchain-robocorp" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_robocorp-{{ version }}.tar.gz
  sha256: 9c07c519acd4da45ab569f5d819b8d1ca0db620c1362c647a46486f43bdbb5c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.2.24,<0.3
    - requests >=2.31.0,<3.0.0
    - types-requests >=2.31.0,<3.0.0

test:
  imports:
    - langchain_robocorp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Robocorp Action Server and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
